# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Étape 1: Installer les dépendances
    - name: Install dependencies
      run: npm ci

    # Étape 2: Exécuter la vérification de type TypeScript
    # Cette étape est cruciale pour détecter les erreurs TS comme TS2322, TS7053, etc.
    - name: Run TypeScript type check
      run: npx tsc --noEmit

    # Étape 3: Exécuter la construction du projet
    # Le 'build' va re-vérifier les types et compiler le code
    - name: Run build
      run: npm run build --if-present

    # Étape 4: Exécuter les tests unitaires
    # Si le projet a des tests, cette étape les lance
    - name: Run tests
      run: npm test
